# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.musicstore: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---

#for h2
spring:
  config:
    activate:
      on-profile: h2

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:musiccatalog-db;DB_CLOSE_DELAY=-1;NON_KEYWORDS=YEAR
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none   #use create to allow jpa to auto-generate from Entity classes; use none to use

    defer-datasource-initialization: true

  sql:
    init:
      platform: h2
      mode: always

server:
  port: 7002

---

# for docker

spring:
  config:
    activate:
      on-profile: docker


  datasource:
    url: jdbc:mysql://mysql2/musiccatalog-db
    username: user
    password: pwd

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create   #use create to allow jpa to auto-generate from Entity classes; use none to use

    defer-datasource-initialization: true

  sql:
    init:
      platform: mysql
      mode: always

server.port: 8080

spring.datasource.hikari.initializationFailTimeout: 60000