package com.musicstore.musiccatalog.mappinglayer;

import com.musicstore.musiccatalog.dataaccesslayer.artist.Artist;
import com.musicstore.musiccatalog.dataaccesslayer.artist.ArtistIdentifier;
import com.musicstore.musiccatalog.dataaccesslayer.artist.ArtistInformation;
import com.musicstore.musiccatalog.presentationlayer.artist.ArtistRequestModel;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings;

@Mapper(componentModel = "spring")
public interface ArtistRequestMapper {
    @Mappings({
            @Mapping(target = "id", ignore = true), // ID is generated by the database
    })
    Artist requestModelToEntity(ArtistRequestModel requestModel, ArtistIdentifier artistIdentifier, ArtistInformation artistInformation);
}



